[default.extend-words]
coordiantes = "coordiantes"

[files]
extend-exclude = [
    "CHANGELOG.md",
    "notebooks/*",
    ".gitignore",
    "**/node_modules/*",
    "**/dist/*",
    "**/build/*",
    "**/target/*",
    "**/public/*",
    "**/src/assets/*",
    "**/fixtures/*",
    "**/data/*",
]
